{
 "title": "Prometheus CPU Metrics",
 "description": "A provisioned dashboard for Prometheus CPU usage.",
 "tags": [
  "prometheus",
  "cpu",
  "9090"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cars-API-3.0.0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "counter{job=\"cars-api-300\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spring Boot App Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"127.0.0.1:8080\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage Percentage (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}