<!DOCTYPE html>
<html style="font-size: 16px;" lang="en"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>SignUp</title>
    <link rel="stylesheet" href="/public/nicepage.css" media="screen" type="text/css" >
    <link rel="stylesheet" href="/public/index.css" media="screen" type="text/css">
    <script class="u-script" type="text/javascript" src="/public/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/public/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 7.14.0, nicepage.com">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css2?display=swap&amp;family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&amp;family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700">
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "public"
}</script>
<body>
    <section class="u-align-center u-clearfix u-container-align-center u-valign-top-lg u-valign-top-md u-valign-top-sm u-section-1" id="carousel_1c8d">
      <div class="data-layout-selected u-clearfix u-gutter-0 u-layout-wrap u-layout-wrap-1">
        <div class="u-layout" style="">
          <div class="u-layout-row" style="">
            <div class="u-align-left u-container-style u-layout-cell u-right-cell u-size-26 u-size-xs-60 u-white u-layout-cell-1">
              <div class="u-container-layout u-valign-bottom-lg u-valign-bottom-md u-valign-bottom-sm u-valign-bottom-xs u-container-layout-1">

                    ${result}
                    <p>
                    <a href="${continue_url}" target="${continue_target}"><input type="button" value="${continue_hdr}" class="u-active-custom-color-5 u-align-center u-border-4 u-border-grey-75 u-btn u-btn-round u-button-style u-custom-color-4 u-hover-custom-color-5 u-hover-feature u-radius-50 u-text-active-white u-text-hover-white u-btn-2" /></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</body>
</html>

