name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -
        name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: fra.ocir.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.AUTH_TOKEN }}
    - name: Build and Push the Docker images to OCIR
      run: |
        cd cars-api-100
        docker build . --build-arg APIGW_PATH=/api -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:1.0.0-free
        docker push fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:1.0.0-free
        cd ..
        cd cars-api-200
        docker build . --build-arg APIGW_PATH=/api -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:2.0.0
        docker push fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:2.0.0
        cd ..
        cd sidecar
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar:1.0.0
        docker push fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar:1.0.0
